//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDelevaryNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERADDRESS
    {
        [System.ComponentModel.DataAnnotations.Key]
        public string ACCOUNTNUM { get; set; }
        public string DATAAREAID { get; set; }
        public int ADDRESSTYPE { get; set; }
        public string STREET { get; set; }
        public string ADDRESS { get; set; }
        public string ZIPCODE { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string COUNTY { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<int> ADDRESSFORMAT { get; set; }
        public string TAXGROUP { get; set; }
        public string PHONE { get; set; }
        public string CELLULARPHONE { get; set; }
        public string EMAIL { get; set; }
        public string CONTACTNAME { get; set; }
    }
}
