//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDelevaryNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTTABLE
    {
        public string ACCOUNTNUM { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string PHONE { get; set; }
        public string TELEFAX { get; set; }
        public string INVOICEACCOUNT { get; set; }
        public string CUSTGROUP { get; set; }
        public string PAYMTERMID { get; set; }
        public string CASHDISC { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<int> BLOCKED { get; set; }
        public Nullable<byte> ONETIMECUSTOMER { get; set; }
        public Nullable<int> ACCOUNTSTATEMENT { get; set; }
        public Nullable<decimal> CREDITMAX { get; set; }
        public Nullable<byte> MANDATORYCREDITLIMIT { get; set; }
        public string DIMENSION { get; set; }
        public string DIMENSION2_ { get; set; }
        public string DIMENSION3_ { get; set; }
        public string VENDACCOUNT { get; set; }
        public string TELEX { get; set; }
        public string COUNTRY { get; set; }
        public string INVENTLOCATION { get; set; }
        public string DLVTERM { get; set; }
        public string DLVMODE { get; set; }
        public string CLEARINGPERIOD { get; set; }
        public string ZIPCODE { get; set; }
        public string STATE { get; set; }
        public string COUNTY { get; set; }
        public string URL { get; set; }
        public string EMAIL { get; set; }
        public string CELLULARPHONE { get; set; }
        public string PHONELOCAL { get; set; }
        public string FREIGHTZONE { get; set; }
        public string CREDITRATING { get; set; }
        public string STATISTICSGROUP { get; set; }
        public string PAYMMODE { get; set; }
        public string BANKACCOUNT { get; set; }
        public string NAMEALIAS { get; set; }
        public string CONTACTPERSONID { get; set; }
        public Nullable<int> INVOICEADDRESS { get; set; }
        public string OURACCOUNTNUM { get; set; }
        public string SALESPOOLID { get; set; }
        public Nullable<byte> INCLTAX { get; set; }
        public string CUSTITEMGROUPID { get; set; }
        public string NUMBERSEQUENCEGROUP { get; set; }
        public string LANGUAGEID { get; set; }
        public string PAYMDAYID { get; set; }
        public string LINEOFBUSINESSID { get; set; }
        public string DESTINATIONCODEID { get; set; }
        public Nullable<int> WEBSALESORDERDISPLAY { get; set; }
        public string PAYMSPEC { get; set; }
        public string BANKCENTRALBANKPURPOSETEXT { get; set; }
        public string BANKCENTRALBANKPURPOSECODE { get; set; }
        public Nullable<int> PRINTMODULETYPE { get; set; }
        public string CITY { get; set; }
        public string STREET { get; set; }
        public string PAGER { get; set; }
        public string SMS { get; set; }
        public Nullable<int> REFZIPCODE { get; set; }
        public string PBACUSTGROUPID { get; set; }
        public string DATAAREAID { get; set; }
        public string VATNUM { get; set; }
        public string TAXGROUP { get; set; }
        public string TAXLICENSENUM { get; set; }
        public Nullable<byte> FORECASTDMPINCLUDE { get; set; }
        public string LINEDISC { get; set; }
        public string SALESGROUP { get; set; }
        public string PRICEGROUP { get; set; }
        public string MULTILINEDISC { get; set; }
        public string ENDDISC { get; set; }
        public string MARKUPGROUP { get; set; }
        public string COMMISSIONGROUP { get; set; }
        public Nullable<int> DEL_QUOTATIONCOPIES { get; set; }
        public Nullable<int> DEL_QUOTATIONORIGINALS { get; set; }
        public Nullable<int> DEL_CONFIRMATIONORIGINALS { get; set; }
        public Nullable<int> DEL_INVOICECOPIES { get; set; }
        public Nullable<int> DEL_INVOICEORIGINALS { get; set; }
        public Nullable<int> DEL_PACKINGSLIPCOPIES { get; set; }
        public Nullable<int> DEL_PACKINGSLIPORIGINALS { get; set; }
        public Nullable<int> DEL_CONFIRMATIONCOPIES { get; set; }
        public string SUPPITEMGROUPID { get; set; }
        public string PACKMATERIALFEELICENSENUM { get; set; }
        public string ORGID { get; set; }
        public Nullable<byte> USEPURCHREQUEST { get; set; }
        public string TAXOFFICE { get; set; }
        public Nullable<byte> NONCHARGABLEACCOUNT { get; set; }
        public Nullable<int> ADDRESSFORMAT { get; set; }
        public string FIRSTNAME { get; set; }
        public string MIDDLENAME { get; set; }
        public string LASTNAME { get; set; }
        public string NAMEPREFIX { get; set; }
        public string NAMESUFFIX { get; set; }
        public byte LOCALLYSAVED { get; set; }
        public Nullable<byte> LOYALTYCUSTOMER { get; set; }
        public Nullable<int> GENDER { get; set; }
        public Nullable<System.DateTime> DATEOFBIRTH { get; set; }
    }
}
