//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDelevaryNote
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DeliveryDbContext : DbContext
    {
        public DeliveryDbContext()
            : base("name=DeliveryDbContext")
        {
        }
    
        public DbSet<CUSTOMERADDRESS> CUSTOMERADDRESS { get; set; }
        public DbSet<CUSTTABLE> CUSTTABLE { get; set; }
        public DbSet<RBOCUSTTABLE> RBOCUSTTABLE { get; set; }
        public DbSet<RBOINFOCODETABLE> RBOINFOCODETABLE { get; set; }
        public DbSet<RBOINFOCODETABLESPECIFIC> RBOINFOCODETABLESPECIFIC { get; set; }
        public DbSet<RBOINFORMATIONSUBCODETABLE> RBOINFORMATIONSUBCODETABLE { get; set; }
        public DbSet<RBOTRANSACTIONINFOCODETRANS> RBOTRANSACTIONINFOCODETRANS { get; set; }
        public DbSet<RBOTRANSACTIONPAYMENTTRAN> RBOTRANSACTIONPAYMENTTRANS { get; set; }
        public DbSet<RBOTRANSACTIONSALESTRANS> RBOTRANSACTIONSALESTRANS { get; set; }
        public DbSet<RBOTRANSACTIONTABLE> RBOTRANSACTIONTABLE { get; set; }
        public DbSet<RBOTRANSACTIONTAXTRAN> RBOTRANSACTIONTAXTRANS { get; set; }
        public DbSet<RBOSTAFFTABLE> RBOSTAFFTABLE { get; set; }
        public DbSet<RBOSTORETABLE> RBOSTORETABLE { get; set; }
    }
}
