//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDelevaryNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBOCUSTTABLE
    {
        [System.ComponentModel.DataAnnotations.Key]
        public string ACCOUNTNUM { get; set; }
        public Nullable<byte> OTHERTENDERINFINALIZING { get; set; }
        public Nullable<byte> POSTASSHIPMENT { get; set; }
        public string DATAAREAID { get; set; }
        public Nullable<byte> USEORDERNUMBERREFERENCE { get; set; }
        public Nullable<int> RECEIPTOPTION { get; set; }
        public string RECEIPTEMAIL { get; set; }
        public Nullable<byte> NONCHARGABLEACCOUNT { get; set; }
        public Nullable<byte> REQUIRESAPPROVAL { get; set; }
    }
}
