//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDelevaryNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBOINFOCODETABLESPECIFIC
    {
        public string REFRELATION { get; set; }
        public Nullable<int> SEQUENCE { get; set; }
        public string INFOCODEID { get; set; }
        public Nullable<byte> INPUTREQUIRED { get; set; }
        public Nullable<int> WHENREQUIRED { get; set; }
        public string REFRELATION2 { get; set; }
        public string REFRELATION3 { get; set; }
        public int REFTABLEID { get; set; }
        public string DATAAREAID { get; set; }
        public Nullable<byte> TRIGGERING { get; set; }
        public string UNITOFMEASURE { get; set; }
        public string SALESTYPEFILTER { get; set; }
        public Nullable<int> USAGECATEGORY { get; set; }
    }
}
