//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDelevaryNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBOINFORMATIONSUBCODETABLE
    {
        [System.ComponentModel.DataAnnotations.Key]
        public string INFOCODEID { get; set; }
        public string SUBCODEID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> TRIGGERFUNCTION { get; set; }
        public string TRIGGERCODE { get; set; }
        public Nullable<byte> NEWSALESLINE { get; set; }
        public Nullable<int> PRICETYPE { get; set; }
        public Nullable<decimal> AMOUNTPERCENT { get; set; }
        public string DATAAREAID { get; set; }
        public Nullable<int> USAGECATEGORY { get; set; }
        public string VARIANTCODE { get; set; }
        public Nullable<byte> VARIANTNEEDED { get; set; }
        public Nullable<byte> QTYLINKEDTOTRIGGERLINE { get; set; }
        public Nullable<int> PRICEHANDLING { get; set; }
        public string LINKEDINFOCODE { get; set; }
        public string UNITOFMEASURE { get; set; }
        public Nullable<decimal> QTYPERUNITOFMEASURE { get; set; }
        public string INFOCODEPROMPT { get; set; }
        public Nullable<int> MAXSELECTION { get; set; }
        public Nullable<byte> SERIALLOTNEEDED { get; set; }
    }
}
