//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDelevaryNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBOSTORETABLE
    {
        public string STOREID { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string STREET { get; set; }
        public string ZIPCODE { get; set; }
        public string CITY { get; set; }
        public string COUNTY { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string PHONE { get; set; }
        public string MANAGERID { get; set; }
        public Nullable<int> OPENFROM { get; set; }
        public Nullable<int> OPENTO { get; set; }
        public string DIMENSION { get; set; }
        public string DIMENSION2_ { get; set; }
        public string DIMENSION3_ { get; set; }
        public string INVENTLOCATION { get; set; }
        public Nullable<int> STATEMENTMETHOD { get; set; }
        public Nullable<byte> ONESTATEMENTPERDAY { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<int> CLOSINGMETHOD { get; set; }
        public string ROUNDINGACCOUNT { get; set; }
        public Nullable<decimal> MAXIMUMPOSTINGDIFFERENCE { get; set; }
        public Nullable<decimal> MAXROUNDINGAMOUNT { get; set; }
        public Nullable<decimal> MAXSHIFTDIFFERENCEAMOUNT { get; set; }
        public Nullable<decimal> MAXTRANSACTIONDIFFERENCEAMOUNT { get; set; }
        public string STATEMENTNUMSEQ { get; set; }
        public string FUNCTIONALITYPROFILE { get; set; }
        public Nullable<byte> CREATELABELSFORZEROPRICE { get; set; }
        public string TERMINALNUMSEQ { get; set; }
        public string STAFFNUMSEQ { get; set; }
        public string ITEMNUMSEQ { get; set; }
        public string DISCOUNTOFFERNUMSEQ { get; set; }
        public string MIXANDMATCHNUMSEQ { get; set; }
        public string MULTIBUYDISCOUNTNUMSEQ { get; set; }
        public Nullable<byte> INVENTORYLOOKUP { get; set; }
        public string REMOVEADDTENDER { get; set; }
        public Nullable<int> TENDERDECLARATIONCALCULATION { get; set; }
        public Nullable<int> MAXIMUMTEXTLENGTHONRECEIPT { get; set; }
        public Nullable<int> NUMBEROFTOPORBOTTOMLINES { get; set; }
        public Nullable<int> ITEMIDONRECEIPT { get; set; }
        public Nullable<decimal> SERVICECHARGEPCT { get; set; }
        public string INCOMEEXEPENSEACCOUNT { get; set; }
        public string SERVICECHARGEPROMPT { get; set; }
        public string STATEMENTVOUCHERNUMSEQ { get; set; }
        public string TAXGROUP { get; set; }
        public Nullable<int> REPLICATIONCOUNTER { get; set; }
        public string ROUNDINGTAXACCOUNT { get; set; }
        public Nullable<decimal> MAXROUNDINGTAXAMOUNT { get; set; }
        public string CULTURENAME { get; set; }
        public string LAYOUTID { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public Nullable<int> MODIFIEDTIME { get; set; }
        public string MODIFIEDBY { get; set; }
        public string DATAAREAID { get; set; }
        public string SQLSERVERNAME { get; set; }
        public string DATABASENAME { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string DEFAULTCUSTACCOUNT { get; set; }
        public Nullable<byte> USEDEFAULTCUSTACCOUNT { get; set; }
        public Nullable<byte> WINDOWSAUTHENTICATION { get; set; }
        public Nullable<byte> HIDETRAININGMODE { get; set; }
        public Nullable<int> ADDRESSFORMAT { get; set; }
        public string TAXOVERRIDEGROUP { get; set; }
        public Nullable<int> USEDESTINATIONBASEDTAX { get; set; }
        public Nullable<int> USECUSTOMERBASEDTAX { get; set; }
        public string TAXIDENTIFICATIONNUMBER { get; set; }
        public Nullable<byte> KEYEDINPRICECONTAINSTAX { get; set; }
        public Nullable<int> CALCDISCFROM { get; set; }
        public Nullable<byte> DISPLAYDISCOUNTINCLTAX { get; set; }
        public Nullable<int> USETAXGROUPFROM { get; set; }
        public int SUSPENDALLOWEOD { get; set; }
        public Nullable<int> StorePriceSetting { get; set; }
        public string TRANSACTIONSERVICEPROFILE { get; set; }
        public string STYLEPROFILE { get; set; }
        public string KEYBOARDCODE { get; set; }
        public string LAYOUTNAME { get; set; }
        public Nullable<System.Guid> KITCHENMANAGERPROFILEID { get; set; }
        public Nullable<byte> USETAXROUNDING { get; set; }
        public Nullable<byte> DISPLAYBALANCEWITHTAX { get; set; }
        public Nullable<System.Guid> RECEIPTPROFILEID { get; set; }
        public byte[] RECEIPTLOGO { get; set; }
        public Nullable<int> RECEIPTLOGOWIDTH { get; set; }
        public string FORMINFOFIELD1 { get; set; }
        public string FORMINFOFIELD2 { get; set; }
        public string FORMINFOFIELD3 { get; set; }
        public string FORMINFOFIELD4 { get; set; }
        public Nullable<int> BARCODESYMBOLOGY { get; set; }
        public Nullable<int> OPERATIONAUDITSETTING { get; set; }
        public Nullable<decimal> STARTAMOUNT { get; set; }
        public Nullable<byte> RETURNSPRINTEDTWICE { get; set; }
        public Nullable<byte> TENDERRECEIPTSAREREPRINTED { get; set; }
    }
}
