//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDelevaryNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBOSTAFFTABLE
    {
        [System.ComponentModel.DataAnnotations.Key]
        public string STAFFID { get; set; }
        public string NAME { get; set; }
        public string STOREID { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<byte> CHANGEPASSWORD { get; set; }
        public Nullable<byte> ALLOWTRANSACTIONVOIDING { get; set; }
        public Nullable<byte> MANAGERPRIVILEGES { get; set; }
        public Nullable<byte> ALLOWXREPORTPRINTING { get; set; }
        public Nullable<byte> ALLOWTENDERDECLARATION { get; set; }
        public Nullable<byte> ALLOWFLOATINGDECLARATION { get; set; }
        public Nullable<int> PRICEOVERRIDE { get; set; }
        public Nullable<decimal> MAXDISCOUNTPCT { get; set; }
        public Nullable<byte> ALLOWCHANGENOVOID { get; set; }
        public Nullable<byte> ALLOWTRANSACTIONSUSPENSION { get; set; }
        public Nullable<byte> ALLOWOPENDRAWERONLY { get; set; }
        public string FIRSTNAME { get; set; }
        public string LASTNAME { get; set; }
        public Nullable<int> EMPLOYMENTTYPE { get; set; }
        public string ADDRESS { get; set; }
        public string STREET { get; set; }
        public string ZIPCODE { get; set; }
        public string CITY { get; set; }
        public string COUNTY { get; set; }
        public string STATE { get; set; }
        public string COUNTRY { get; set; }
        public string DEL_PHONELOCAL { get; set; }
        public string PHONEWORK { get; set; }
        public Nullable<byte> BLOCKED { get; set; }
        public Nullable<System.DateTime> BLOCKINGDATE { get; set; }
        public Nullable<byte> LEFTHANDED { get; set; }
        public string PERMISSIONGROUPID { get; set; }
        public string ZREPORTID { get; set; }
        public string NAMEONRECEIPT { get; set; }
        public string PAYROLLNUMBER { get; set; }
        public Nullable<byte> CONTINUEONTSERRORS { get; set; }
        public string PHONEHOME { get; set; }
        public Nullable<decimal> MAXTOTALDISCOUNTPCT { get; set; }
        public string LAYOUTID { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public Nullable<int> MODIFIEDTIME { get; set; }
        public string MODIFIEDBY { get; set; }
        public string DATAAREAID { get; set; }
        public string VISUALPROFILE { get; set; }
        public string OPERATORCULTURE { get; set; }
        public decimal MAXLINEDISCOUNTAMOUNT { get; set; }
        public decimal MAXTOTALDISCOUNTAMOUNT { get; set; }
        public decimal MAXLINERETURNAMOUNT { get; set; }
        public decimal MAXTOTALRETURNAMOUNT { get; set; }
        public string KEYBOARDCODE { get; set; }
        public string LAYOUTNAME { get; set; }
    }
}
