//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDelevaryNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBOTRANSACTIONTAXTRAN
    {
        public string TRANSACTIONID { get; set; }
        public decimal LINENUM { get; set; }
        public decimal TAXLINENUM { get; set; }
        public string DATAAREAID { get; set; }
        public string TAXGROUP { get; set; }
        public string TAXCODE { get; set; }
        public Nullable<decimal> TAXPCT { get; set; }
        public Nullable<decimal> TAXAMOUNT { get; set; }
        public Nullable<decimal> TAXROUNDOFF { get; set; }
        public Nullable<int> TAXROUNDOFFTYPE { get; set; }
        public Nullable<decimal> PRICEWITHTAX { get; set; }
        public byte TRANSHEADER { get; set; }
        public string STORE { get; set; }
        public string TERMINAL { get; set; }
        public int REPLICATIONCOUNTER { get; set; }
        public Nullable<byte> REPLICATED { get; set; }
        public string TAXCODERECEIPTDISPLAY { get; set; }
        public string TAXGROUPRECEIPTDISPLAY { get; set; }
        public Nullable<byte> TAXEXEMPT { get; set; }
        public string TAXEXEMPTIONCODE { get; set; }
    }
}
