//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDelevaryNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBOTRANSACTIONSALESTRANS
    {
        [System.ComponentModel.DataAnnotations.Key]
        public string TRANSACTIONID { get; set; }
        public decimal LINENUM { get; set; }
        public string RECEIPTID { get; set; }
        public string BARCODE { get; set; }
        public string ITEMID { get; set; }
        public string ITEMDEPARTMENTID { get; set; }
        public string ITEMGROUPID { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> NETPRICE { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string TAXGROUP { get; set; }
        public Nullable<int> TRANSACTIONSTATUS { get; set; }
        public Nullable<decimal> DISCAMOUNT { get; set; }
        public Nullable<decimal> COSTAMOUNT { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public Nullable<int> TRANSTIME { get; set; }
        public string SHIFT { get; set; }
        public Nullable<System.DateTime> SHIFTDATE { get; set; }
        public Nullable<decimal> NETAMOUNT { get; set; }
        public string DISCOFFERID { get; set; }
        public string DISCGROUPID { get; set; }
        public Nullable<decimal> STDNETPRICE { get; set; }
        public Nullable<decimal> DISCAMOUNTFROMSTDPRICE { get; set; }
        public string STATEMENTID { get; set; }
        public string CUSTACCOUNT { get; set; }
        public string SECTION { get; set; }
        public string SHELF { get; set; }
        public string STATEMENTCODE { get; set; }
        public Nullable<int> TRANSACTIONCODE { get; set; }
        public string STORE { get; set; }
        public Nullable<byte> ITEMIDSCANNED { get; set; }
        public Nullable<byte> KEYBOARDITEMENTRY { get; set; }
        public Nullable<byte> PRICEINBARCODE { get; set; }
        public Nullable<byte> PRICECHANGE { get; set; }
        public Nullable<byte> WEIGHTMANUALLYENTERED { get; set; }
        public Nullable<byte> LINEWASDISCOUNTED { get; set; }
        public Nullable<byte> SCALEITEM { get; set; }
        public Nullable<byte> WEIGHTITEM { get; set; }
        public Nullable<byte> RETURNNOSALE { get; set; }
        public Nullable<byte> ITEMCORRECTEDLINE { get; set; }
        public Nullable<int> SALESTYPE { get; set; }
        public Nullable<byte> LINKEDITEMNOTORIGINAL { get; set; }
        public Nullable<decimal> ORIGINALOFLINKEDITEMLIST { get; set; }
        public string TERMINALID { get; set; }
        public string STAFF { get; set; }
        public string ITEMPOSTINGGROUP { get; set; }
        public Nullable<decimal> TOTALROUNDEDAMOUNT { get; set; }
        public Nullable<int> COUNTER { get; set; }
        public int REPLICATIONCOUNTER { get; set; }
        public string VARIANTID { get; set; }
        public Nullable<decimal> LINEDSCAMOUNT { get; set; }
        public Nullable<byte> REPLICATED { get; set; }
        public Nullable<decimal> CUSTDISCAMOUNT { get; set; }
        public Nullable<decimal> INFOCODEDISCAMOUNT { get; set; }
        public Nullable<decimal> CUSTINVOICEDISCAMOUNT { get; set; }
        public string UNIT { get; set; }
        public Nullable<decimal> UNITQTY { get; set; }
        public Nullable<decimal> UNITPRICE { get; set; }
        public Nullable<decimal> TAXAMOUNT { get; set; }
        public Nullable<decimal> TOTALDISCAMOUNT { get; set; }
        public Nullable<decimal> TOTALDISCPCT { get; set; }
        public Nullable<decimal> TOTALDISCINFOCODELINENUM { get; set; }
        public Nullable<int> PERIODICDISCTYPE { get; set; }
        public Nullable<decimal> PERIODICDISCAMOUNT { get; set; }
        public Nullable<decimal> DISCOUNTAMOUNTFORPRINTING { get; set; }
        public string STAFFID { get; set; }
        public string PERIODICDISCGROUP { get; set; }
        public string INVENTTRANSID { get; set; }
        public string INVENTDIMID { get; set; }
        public string PURCHID { get; set; }
        public string FILELOGID { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public Nullable<int> MODIFIEDTIME { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<int> MODIFIEDTRANSACTIONID { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<int> CREATEDTIME { get; set; }
        public string CREATEDBY { get; set; }
        public Nullable<int> CREATEDTRANSACTIONID { get; set; }
        public string DATAAREAID { get; set; }
        public Nullable<int> PUMPID { get; set; }
        public string PRESCRIPTIONID { get; set; }
        public string COMMENT { get; set; }
        public Nullable<decimal> LINEDISCPCT { get; set; }
        public Nullable<decimal> WHOLEDISCAMOUNTWITHTAX { get; set; }
        public Nullable<decimal> TOTALDISCAMOUNTWITHTAX { get; set; }
        public Nullable<decimal> LINEDISCAMOUNTWITHTAX { get; set; }
        public Nullable<decimal> PERIODICDISCAMOUNTWITHTAX { get; set; }
        public string INVENTBATCHID { get; set; }
        public Nullable<byte> GIFTCARD { get; set; }
        public string INVENTSERIALID { get; set; }
        public string RFIDTAGID { get; set; }
        public string RETURNTRANSACTIONID { get; set; }
        public Nullable<decimal> RETURNQTY { get; set; }
        public Nullable<int> ITEMTYPE { get; set; }
        public Nullable<int> SOURCELINENUM { get; set; }
        public string CREDITMEMONUMBER { get; set; }
        public Nullable<byte> TAXINCLINPRICE { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<decimal> OILTAX { get; set; }
        public Nullable<decimal> RETURNLINEID { get; set; }
        public Nullable<byte> ISINFOCODEITEM { get; set; }
        public Nullable<System.DateTime> INVENTBATCHEXPDATE { get; set; }
        public string TENDERRESTRICTIONID { get; set; }
        public Nullable<decimal> PRICEUNIT { get; set; }
        public Nullable<decimal> NETAMOUNTINCLTAX { get; set; }
        public string DOSAGETYPE { get; set; }
        public string DOSAGESTRENGTHUNIT { get; set; }
        public Nullable<decimal> DOSAGESTRENGTH { get; set; }
        public Nullable<decimal> DOSAGEUNITQUANTITY { get; set; }
        public string TAXITEMGROUP { get; set; }
        public string STORETAXGROUP { get; set; }
        public string ORIGINALTAXGROUP { get; set; }
        public string ORIGINALTAXITEMGROUP { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<byte> TAXEXEMPT { get; set; }
        public string HOSPITALITYSALESTYPE { get; set; }
        public Nullable<decimal> ORIGINALPRICE { get; set; }
        public Nullable<decimal> ORIGINALPRICEWITHTAX { get; set; }
        public string RETURNRECEIPTID { get; set; }
        public string RETURNSTOREID { get; set; }
        public string RETURNTERMINALID { get; set; }
    }
}
