//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDelevaryNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBOTRANSACTIONTABLE
    {
        public string TRANSACTIONID { get; set; }
        public Nullable<int> TYPE { get; set; }
        public string RECEIPTID { get; set; }
        public string STORE { get; set; }
        public string TERMINAL { get; set; }
        public string STAFF { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public Nullable<int> TRANSTIME { get; set; }
        public string SHIFT { get; set; }
        public Nullable<System.DateTime> SHIFTDATE { get; set; }
        public Nullable<int> WRONGSHIFT { get; set; }
        public string INFOCODEDISCGROUP { get; set; }
        public string CUSTACCOUNT { get; set; }
        public Nullable<int> TRANSCODE { get; set; }
        public Nullable<decimal> SALESPAYMENTDIFFERENCE { get; set; }
        public Nullable<decimal> NETAMOUNT { get; set; }
        public Nullable<decimal> COSTAMOUNT { get; set; }
        public Nullable<decimal> GROSSAMOUNT { get; set; }
        public Nullable<decimal> PAYMENTAMOUNT { get; set; }
        public Nullable<decimal> DISCAMOUNT { get; set; }
        public Nullable<decimal> CUSTDISCAMOUNT { get; set; }
        public Nullable<decimal> TOTALDISCAMOUNT { get; set; }
        public Nullable<decimal> NUMBEROFITEMS { get; set; }
        public Nullable<decimal> AMOUNTTOACCOUNT { get; set; }
        public Nullable<decimal> ROUNDEDAMOUNT { get; set; }
        public Nullable<int> ENTRYSTATUS { get; set; }
        public Nullable<int> NUMBEROFINVOICES { get; set; }
        public Nullable<decimal> NUMBEROFITEMLINES { get; set; }
        public string STATEMENTCODE { get; set; }
        public string STATEMENTID { get; set; }
        public string REFUNDRECEIPTID { get; set; }
        public Nullable<decimal> INCOMEEXPENSEAMOUNT { get; set; }
        public Nullable<byte> TOACCOUNT { get; set; }
        public Nullable<int> NUMBEROFPAYMENTLINES { get; set; }
        public Nullable<byte> SALEISRETURNSALE { get; set; }
        public Nullable<int> COUNTER { get; set; }
        public Nullable<int> TIMEWHENTOTALPRESSED { get; set; }
        public Nullable<int> TIMEWHENTRANSCLOSED { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<int> TRANSTABLEID { get; set; }
        public Nullable<byte> OPENDRAWER { get; set; }
        public Nullable<byte> REPLICATED { get; set; }
        public int REPLICATIONCOUNTER { get; set; }
        public Nullable<int> REPLICATIONCOUNTERFROMORIGIN { get; set; }
        public Nullable<byte> INCLUDEDINSTATISTICS { get; set; }
        public string RETRIEVEDFROMRECEIPTID { get; set; }
        public string ZREPORTID { get; set; }
        public string CREATEDONPOSTERMINAL { get; set; }
        public Nullable<byte> POSTASSHIPMENT { get; set; }
        public Nullable<byte> ITEMSPOSTED { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public Nullable<int> MODIFIEDTIME { get; set; }
        public string MODIFIEDBY { get; set; }
        public Nullable<System.DateTime> CREATEDDATE { get; set; }
        public Nullable<int> CREATEDTIME { get; set; }
        public string CREATEDBY { get; set; }
        public string DATAAREAID { get; set; }
        public string DESCRIPTION { get; set; }
        public string CUSTPURCHASEORDER { get; set; }
        public string COMMENT { get; set; }
        public string INVOICECOMMENT { get; set; }
        public Nullable<decimal> SALESORDERAMOUNT { get; set; }
        public Nullable<decimal> SALESINVOICEAMOUNT { get; set; }
        public string RECEIPTEMAIL { get; set; }
        public Nullable<decimal> EXCHRATE { get; set; }
        public Nullable<decimal> MARKUPAMOUNT { get; set; }
        public string MARKUPDESCRIPTION { get; set; }
        public string ORGTRANSSTORE { get; set; }
        public string ORGTRANSTERMINAL { get; set; }
        public string ORGTRANSACTIONID { get; set; }
        public string ORGRECEIPTID { get; set; }
        public Nullable<decimal> OILTAX { get; set; }
        public Nullable<byte> TAXINCLINPRICE { get; set; }
        public Nullable<byte> TAXEXEMPT { get; set; }
        public Nullable<byte> UNCONCLUDEDTRANS { get; set; }
        public bool INVENTORYUPDATED { get; set; }
        public string SALESSEQUENCEID { get; set; }
        public Nullable<System.DateTime> BUSINESSDAY { get; set; }
        public Nullable<bool> TRNGENERATED { get; set; }
        public Nullable<System.DateTime> BUSINESSSYSTEMDAY { get; set; }
    }
}
