//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDelevaryNote
{
    using System;
    using System.Collections.Generic;
    
    public partial class RBOTRANSACTIONPAYMENTTRAN
    {
        public string TRANSACTIONID { get; set; }
        public decimal LINENUM { get; set; }
        public string RECEIPTID { get; set; }
        public string STATEMENTCODE { get; set; }
        public string CARDTYPEID { get; set; }
        public Nullable<decimal> EXCHRATE { get; set; }
        public string TENDERTYPE { get; set; }
        public Nullable<decimal> AMOUNTTENDERED { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> AMOUNTCUR { get; set; }
        public string CARDORACCOUNT { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public Nullable<int> TRANSTIME { get; set; }
        public string SHIFT { get; set; }
        public Nullable<System.DateTime> SHIFTDATE { get; set; }
        public string STAFF { get; set; }
        public string STORE { get; set; }
        public string TERMINAL { get; set; }
        public Nullable<int> TRANSACTIONSTATUS { get; set; }
        public string STATEMENTID { get; set; }
        public Nullable<byte> MANAGERKEYLIVE { get; set; }
        public Nullable<byte> CHANGELINE { get; set; }
        public Nullable<int> COUNTER { get; set; }
        public int REPLICATIONCOUNTER { get; set; }
        public Nullable<int> MESSAGENUM { get; set; }
        public Nullable<byte> REPLICATED { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public string ZREPORTID { get; set; }
        public Nullable<System.DateTime> MODIFIEDDATE { get; set; }
        public string DATAAREAID { get; set; }
        public Nullable<decimal> MARKUPAMOUNT { get; set; }
        public string AUTHENTICATIONCODE { get; set; }
        public string GIFTORCREDITID { get; set; }
        public string BATCHID { get; set; }
        public string EFTAUTHENTICATIONCODE { get; set; }
        public string GIFTCARDID { get; set; }
        public string CREDITVOUCHERID { get; set; }
        public string LOYALTYCARDID { get; set; }
        public Nullable<decimal> EXCHRATEMST { get; set; }
        public Nullable<decimal> AMOUNTMST { get; set; }
        public Nullable<decimal> LOYALTYPOINTS { get; set; }
        public string COMMENT { get; set; }
        public Nullable<byte> CARDNUMBERHIDDEN { get; set; }
        public string CARDNAME { get; set; }
        public string CARDISSUER { get; set; }
        public string EXPIRYDATE { get; set; }
        public string CARDHOLDERNAME { get; set; }
        public Nullable<int> CARDENTRYTYPE { get; set; }
        public string CARDBIN { get; set; }
        public string MERCHANTID { get; set; }
        public string AUTHCODE { get; set; }
        public string MESSAGE { get; set; }
        public string RESPONSECODE { get; set; }
        public string DRIVERID { get; set; }
        public string VEHICLEID { get; set; }
        public Nullable<int> ODOMETERREADING { get; set; }
        public string DESCRIPTION { get; set; }
        public string CHECKID { get; set; }
    }
}
