//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LSDelevaryNote.ERPServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string branch_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string branch_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string item_nameField;
        
        private int? quantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string branch_code {
            get {
                return this.branch_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.branch_codeField, value) != true)) {
                    this.branch_codeField = value;
                    this.RaisePropertyChanged("branch_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string branch_name {
            get {
                return this.branch_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.branch_nameField, value) != true)) {
                    this.branch_nameField = value;
                    this.RaisePropertyChanged("branch_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string item_code {
            get {
                return this.item_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.item_codeField, value) != true)) {
                    this.item_codeField = value;
                    this.RaisePropertyChanged("item_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string item_name {
            get {
                return this.item_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.item_nameField, value) != true)) {
                    this.item_nameField = value;
                    this.RaisePropertyChanged("item_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int? quantity {
            get {
                return this.quantityField;
            }
            set {
                if ((this.quantityField.Equals(value) != true)) {
                    this.quantityField = value;
                    this.RaisePropertyChanged("quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ERPServiceReference.GetOnhandQuantitySoap")]
    public interface GetOnhandQuantitySoap {
        
        // CODEGEN: Generating message contract since element name GetQuantityResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuantity", ReplyAction="*")]
        LSDelevaryNote.ERPServiceReference.GetQuantityResponse GetQuantity(LSDelevaryNote.ERPServiceReference.GetQuantityRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuantityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuantity", Namespace="http://tempuri.org/", Order=0)]
        public LSDelevaryNote.ERPServiceReference.GetQuantityRequestBody Body;
        
        public GetQuantityRequest() {
        }
        
        public GetQuantityRequest(LSDelevaryNote.ERPServiceReference.GetQuantityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetQuantityRequestBody {
        
        public GetQuantityRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetQuantityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetQuantityResponse", Namespace="http://tempuri.org/", Order=0)]
        public LSDelevaryNote.ERPServiceReference.GetQuantityResponseBody Body;
        
        public GetQuantityResponse() {
        }
        
        public GetQuantityResponse(LSDelevaryNote.ERPServiceReference.GetQuantityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetQuantityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LSDelevaryNote.ERPServiceReference.Item[] GetQuantityResult;
        
        public GetQuantityResponseBody() {
        }
        
        public GetQuantityResponseBody(LSDelevaryNote.ERPServiceReference.Item[] GetQuantityResult) {
            this.GetQuantityResult = GetQuantityResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetOnhandQuantitySoapChannel : LSDelevaryNote.ERPServiceReference.GetOnhandQuantitySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetOnhandQuantitySoapClient : System.ServiceModel.ClientBase<LSDelevaryNote.ERPServiceReference.GetOnhandQuantitySoap>, LSDelevaryNote.ERPServiceReference.GetOnhandQuantitySoap {
        
        public GetOnhandQuantitySoapClient() {
        }
        
        public GetOnhandQuantitySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetOnhandQuantitySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetOnhandQuantitySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetOnhandQuantitySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LSDelevaryNote.ERPServiceReference.GetQuantityResponse LSDelevaryNote.ERPServiceReference.GetOnhandQuantitySoap.GetQuantity(LSDelevaryNote.ERPServiceReference.GetQuantityRequest request) {
            return base.Channel.GetQuantity(request);
        }
        
        public LSDelevaryNote.ERPServiceReference.Item[] GetQuantity() {
            LSDelevaryNote.ERPServiceReference.GetQuantityRequest inValue = new LSDelevaryNote.ERPServiceReference.GetQuantityRequest();
            inValue.Body = new LSDelevaryNote.ERPServiceReference.GetQuantityRequestBody();
            LSDelevaryNote.ERPServiceReference.GetQuantityResponse retVal = ((LSDelevaryNote.ERPServiceReference.GetOnhandQuantitySoap)(this)).GetQuantity(inValue);
            return retVal.Body.GetQuantityResult;
        }
    }
}
